before_script:
  - sudo apt-get -qq update
  - npm install -g gulp-cli
  - gem install jekyll
  - npm install
script: gulp deploy
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: develop