# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
baseurl: ""
url: "daviddudson@github.io"

# User settings
username: David Dudson

user_title: Software Developer
email: davidjohndudson@gmail.com
twitter_username: bigdavenz1
github_username:  daviddudson
gplus_username:  bigdavenz
linkedin:  daviddudson

google-analytics:
  id: 'UA-42525615-1'

exclude: ['package.json', 'src' , 'node_modules']
