text:
  This site is a very simple jekyll site.
  It's designed to deploy on push.
  The release process is as follows

steps:
 - Push changes to develop branch
 - Travis converts to static via gulp
 - Travis pushes result to master
 - Github builds jekyll site
 - Github deploys the site